### ISSUE TITLE
Mauna Loa Data

### ISSUE THREAD

**Issue by ceroddy6** [gge-ucd/wRangling_Seminar#1]
I have loaded all of the time series data from the previous lectures, but I can't seem to figure out which one is data_output/mauna_loa_met_2001_minute.rda to complete the time series data challenge. Was I supposed to create that and if so, can you direct me to the right file that explains what I am supposed to do to create it. All I have is a folder with a bunch of text files.  Thanks!

**Comment by ecbolas** [comment]
Also having trouble converting the zip file into one usable file

**Comment by ryanpeek** [comment]
Hi all,
I think there's two parts here that you'll want to check out. If you are interested in figuring out how we **merged** the 12 different mauna_loa_met files (1 per month) into one big file (which we saved as both an **.rda** and an **.rds**), you'll want to see the code that is in the **wRangling_Seminar/documents/ice_C02_web_data.Rmd** file. Particularly, the section that says "**Read in Multiple Files**" which gives code for reading all those files in and merging (using `unnest` or `rbind` functions).

In order for that code to run, you need to have all 12 mauna_loa.txt files (unzipped) and in the right location. 

If you want to skip over this part, you would start by saving the `rda` or `rds` files (go to *wRangling_Seminar/data_output/mauna_loa_met_2001_minute.rda* and click on the download button), and use those in the R-timeseries code.

Hope this helps 👍 .

**Comment by ryanpeek** [comment]
moving this over to the discussion repo
